/*
 * Please do not edit this file, it is autogenerated.
 */
 
#pragma once 
#include "String.hpp"
#include "TokenType.hpp"


String stringify_token(TokenType token) {
    if (token == TokenType::NUMBER) return "NUMBER";
    if (token == TokenType::STRING) return "STRING";
    if (token == TokenType::EQUALS) return "EQUALS";
    if (token == TokenType::PLUS) return "PLUS";
    if (token == TokenType::MINUS) return "MINUS";
    if (token == TokenType::STAR) return "STAR";
    if (token == TokenType::FORWARD_SLASH) return "FORWARD_SLASH";
    if (token == TokenType::BACKWARDS_SLASH) return "BACKWARDS_SLASH";
    if (token == TokenType::LEFT_PAREN) return "LEFT_PAREN";
    if (token == TokenType::RIGHT_PAREN) return "RIGHT_PAREN";
    if (token == TokenType::LEFT_BRACE) return "LEFT_BRACE";
    if (token == TokenType::RIGHT_BRACE) return "RIGHT_BRACE";
    if (token == TokenType::LESS_THAN) return "LESS_THAN";
    if (token == TokenType::GREATER_THAN) return "GREATER_THAN";
    if (token == TokenType::COLON) return "COLON";
    if (token == TokenType::DEF) return "DEF";
    if (token == TokenType::PASS) return "PASS";
    if (token == TokenType::CLASS) return "CLASS";
    if (token == TokenType::RETURN) return "RETURN";
    if (token == TokenType::YIELD) return "YIELD";
    if (token == TokenType::ASYNC) return "ASYNC";
    if (token == TokenType::AWAIT) return "AWAIT";
    if (token == TokenType::IDENTIFIER) return "IDENTIFIER";
    if (token == TokenType::NEW_LINE) return "NEW_LINE";
    if (token == TokenType::INVALID) return "INVALID";

    return "TOKEN_NOT_REGISTERED";
}
    